//! Node-Detail-Snapshot fuer die Flutter-Properties-Ansicht.

use fs25_auto_drive_engine::core::NodeFlag;
use serde::{Deserialize, Serialize};

/// Vollstaendiger NodeFlag-Satz fuer Properties-Anzeige und -Bearbeitung.
///
/// Bildet alle Core-NodeFlag-Varianten 1:1 ab, damit Flutter die
/// vollstaendige Domaene darstellen kann.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HostNodeFlag {
    /// Normaler Wegpunkt.
    Regular,
    /// Nebenstrassen-Node.
    SubPrio,
    /// Importierter Auto-Generated-Flag.
    AutoGenerated,
    /// Reservierter Node.
    Reserved,
    /// Importierter spline-generierter Flag.
    SplineGenerated,
    /// Warn-Node.
    Warning,
    /// Durch Rounding erzeugter Corner-Node.
    RoundedCorner,
}

impl From<&NodeFlag> for HostNodeFlag {
    fn from(flag: &NodeFlag) -> Self {
        match flag {
            NodeFlag::Regular => Self::Regular,
            NodeFlag::SubPrio => Self::SubPrio,
            NodeFlag::AutoGenerated => Self::AutoGenerated,
            NodeFlag::Reserved => Self::Reserved,
            NodeFlag::SplineGenerated => Self::SplineGenerated,
            NodeFlag::Warning => Self::Warning,
            NodeFlag::RoundedCorner => Self::RoundedCorner,
        }
    }
}

/// Nachbar-Info eines Nodes fuer das Properties-Panel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HostNodeNeighbor {
    /// ID des Nachbar-Nodes.
    pub neighbor_id: u64,
    /// Winkel der Verbindung in Radiant.
    pub angle: f32,
    /// `true`, wenn die Verbindung von diesem Node zum Nachbar verlaeuft.
    pub is_outgoing: bool,
}

/// Marker-Kurzinfo am Node (falls vorhanden).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HostNodeMarkerInfo {
    /// Name des Markers.
    pub name: String,
    /// Gruppe des Markers.
    pub group: String,
}

/// Vollstaendiger Node-Detail-Snapshot fuer das Flutter-Properties-Panel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HostNodeDetails {
    /// Node-ID.
    pub id: u64,
    /// Weltposition als `[x, z]`.
    pub position: [f32; 2],
    /// Aktueller Node-Flag.
    pub flag: HostNodeFlag,
    /// Verbundene Nachbarn mit Richtungsinfo.
    pub neighbors: Vec<HostNodeNeighbor>,
    /// Marker-Info, falls an diesem Node ein Marker sitzt.
    pub marker: Option<HostNodeMarkerInfo>,
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{HostNodeDetails, HostNodeFlag, HostNodeMarkerInfo, HostNodeNeighbor};
    use crate::dto::HostSessionAction;

    #[test]
    fn host_node_details_roundtrip_json() {
        let details = HostNodeDetails {
            id: 42,
            position: [10.5, -3.25],
            flag: HostNodeFlag::Warning,
            neighbors: vec![
                HostNodeNeighbor {
                    neighbor_id: 7,
                    angle: 0.75,
                    is_outgoing: true,
                },
                HostNodeNeighbor {
                    neighbor_id: 9,
                    angle: 2.5,
                    is_outgoing: false,
                },
            ],
            marker: Some(HostNodeMarkerInfo {
                name: "Hof".to_string(),
                group: "All".to_string(),
            }),
        };

        let payload = serde_json::to_value(&details)
            .expect("HostNodeDetails muss als JSON serialisierbar sein");
        let parsed: HostNodeDetails = serde_json::from_value(payload)
            .expect("HostNodeDetails muss aus JSON zuruecklesbar sein");

        assert_eq!(parsed, details);
    }

    #[test]
    fn host_node_flag_serializes_all_variants_as_expected() {
        let cases = [
            (HostNodeFlag::Regular, "regular"),
            (HostNodeFlag::SubPrio, "sub_prio"),
            (HostNodeFlag::AutoGenerated, "auto_generated"),
            (HostNodeFlag::Reserved, "reserved"),
            (HostNodeFlag::SplineGenerated, "spline_generated"),
            (HostNodeFlag::Warning, "warning"),
            (HostNodeFlag::RoundedCorner, "rounded_corner"),
        ];

        for (flag, expected) in cases {
            let payload = serde_json::to_value(flag)
                .expect("HostNodeFlag muss als JSON serialisierbar sein");
            assert_eq!(payload, json!(expected));

            let parsed: HostNodeFlag = serde_json::from_value(payload)
                .expect("HostNodeFlag muss aus JSON zuruecklesbar sein");
            assert_eq!(parsed, flag);
        }
    }

    #[test]
    fn host_session_action_query_node_details_roundtrip_json() {
        let action = HostSessionAction::QueryNodeDetails { node_id: 42 };

        let payload = serde_json::to_value(&action)
            .expect("QueryNodeDetails muss als JSON serialisierbar sein");
        assert_eq!(payload, json!({ "kind": "query_node_details", "node_id": 42 }));

        let parsed: HostSessionAction = serde_json::from_value(payload)
            .expect("QueryNodeDetails muss aus JSON zuruecklesbar sein");
        assert_eq!(parsed, action);
    }

    #[test]
    fn host_session_action_set_node_flag_roundtrip_json() {
        let action = HostSessionAction::SetNodeFlag {
            node_id: 17,
            flag: HostNodeFlag::RoundedCorner,
        };

        let payload = serde_json::to_value(&action)
            .expect("SetNodeFlag muss als JSON serialisierbar sein");
        assert_eq!(
            payload,
            json!({
                "kind": "set_node_flag",
                "node_id": 17,
                "flag": "rounded_corner"
            })
        );

        let parsed: HostSessionAction = serde_json::from_value(payload)
            .expect("SetNodeFlag muss aus JSON zuruecklesbar sein");
        assert_eq!(parsed, action);
    }
}