//! Domaenentypen fuer Wegpunkte im AutoDrive-Netzwerk.

use glam::Vec2;

/// Typ des Wegpunkts (Flags aus AutoDrive-Mod: `FLAG_*`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeFlag {
    /// Normaler Wegpunkt – mindestens ein Hauptstrassenanschluss
    Regular = 0,
    /// Nebenstrasse (SubPrio) – nur Nebenstrassen muenden in diesen Node
    SubPrio = 1,
    /// Auto-generiert (nur beim Import, wird zu Regular konvertiert)
    AutoGenerated = 2,
    /// Reserviert
    Reserved = 3,
    /// Spline-generiert (nur beim Import, wird zu Regular konvertiert)
    SplineGenerated = 4,
    /// Warnung
    Warning = 5,
    /// Eckenverrundungs-Node: generiert durch Rounding, aus Distanzberechnung ausgeschlossen.
    /// Wird beim XML-Export als Regular (0) geschrieben (AutoDrive-Kompatibilitaet).
    RoundedCorner = 6,
}

impl NodeFlag {
    /// Konvertiert eine Zahl in den entsprechenden Flag-Typ.
    /// Bereinigt automatisch Flags 2 und 4 zu 0 (AutoGenerated/SplineGenerated aus aelteren Versionen).
    pub fn from_u32(value: u32) -> Self {
        match value {
            1 => NodeFlag::SubPrio,
            2 | 4 => NodeFlag::Regular, // Auto-Bereinigung
            3 => NodeFlag::Reserved,
            5 => NodeFlag::Warning,
            6 => NodeFlag::RoundedCorner,
            _ => NodeFlag::Regular,
        }
    }

    /// Gibt den numerischen Flag-Wert zurueck (interner Wert).
    pub fn to_u32(self) -> u32 {
        match self {
            NodeFlag::Regular => 0,
            NodeFlag::SubPrio => 1,
            NodeFlag::AutoGenerated => 2,
            NodeFlag::Reserved => 3,
            NodeFlag::SplineGenerated => 4,
            NodeFlag::Warning => 5,
            NodeFlag::RoundedCorner => 6,
        }
    }

    /// Gibt den Flag-Wert fuer den XML-Export zurueck.
    /// `RoundedCorner` wird als `Regular` (0) exportiert, da AutoDrive Flag 6 nicht kennt.
    pub fn to_export_u32(self) -> u32 {
        match self {
            NodeFlag::RoundedCorner => 0,
            other => other.to_u32(),
        }
    }
}

/// Ein Wegpunkt im AutoDrive-Netzwerk.
#[derive(Debug, Clone)]
pub struct MapNode {
    /// Eindeutige ID (vom User/AutoDrive vergeben)
    pub id: u64,
    /// Position in Welt-Koordinaten (2D)
    pub position: Vec2,
    /// Typ/Flag des Wegpunkts
    pub flag: NodeFlag,
}

impl MapNode {
    /// Erstellt einen neuen Wegpunkt
    pub fn new(id: u64, position: Vec2, flag: NodeFlag) -> Self {
        Self { id, position, flag }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flag_conversion() {
        assert_eq!(NodeFlag::from_u32(0), NodeFlag::Regular);
        assert_eq!(NodeFlag::from_u32(1), NodeFlag::SubPrio);
        assert_eq!(NodeFlag::from_u32(2), NodeFlag::Regular); // Auto-Bereinigung
        assert_eq!(NodeFlag::from_u32(4), NodeFlag::Regular); // Auto-Bereinigung
        assert_eq!(NodeFlag::from_u32(5), NodeFlag::Warning);
        assert_eq!(NodeFlag::from_u32(6), NodeFlag::RoundedCorner);
    }

    #[test]
    fn test_export_flag_rounded_corner() {
        // RoundedCorner wird beim Export als Regular (0) geschrieben
        assert_eq!(NodeFlag::RoundedCorner.to_export_u32(), 0);
        assert_eq!(NodeFlag::Warning.to_export_u32(), 5);
        assert_eq!(NodeFlag::SubPrio.to_export_u32(), 1);
    }

    #[test]
    fn test_rounded_corner_roundtrip() {
        // from_u32(6) == RoundedCorner, to_u32() == 6 (interner Wert)
        assert_eq!(NodeFlag::from_u32(6), NodeFlag::RoundedCorner);
        assert_eq!(NodeFlag::RoundedCorner.to_u32(), 6);
        // Export muss weiterhin 0 liefern (AutoDrive-Kompatibilitaet)
        assert_eq!(NodeFlag::RoundedCorner.to_export_u32(), 0);
    }
}
